### ISSUE TITLE
No MASTER_TAB re-election on Firefox iframe

### ISSUE THREAD

**Issue by nevcos** [tejacques/crosstab#51]
No reelection occurring after MASTER_TAB refresh on a iframe.

Steps for reproducing:
1. Open Firefox 40;
2. Open 2 tabs with Javascript running on an iframe;
3. Refresh the master tab;

Result:
- There are no MASTER_TAB elected. The MASTER_TAB value on localStorage is pointing to a not existent tab:

```
{
  "14488945006270009571866": {
    "id": "14488945006270009571866",
    "lastUpdated": 1448895188388
  },
  "MASTER_TAB": {
    "id": "14488944316952140456572",
    "lastUpdated": 1448894501270
  },
  "14488945024330039719292": {
    "id": "14488945024330039719292",
    "lastUpdated": 1448895189539
  }
}
```

**Comment by tejacques** [comment]
Hey @nevcos,

I just realized I'm incredibly dumb and never pushed out the fix for this to NPM. I'll do that ASAP.

**Comment by nevcos** [comment]
Hi @tejacques,

That's good news! We have an important release tomorrow morning. 

Thanks

**Comment by tejacques** [comment]
Ok less good news -- turns out I am not as dumb as I thought, and the latest fix is up on `npm`. That means this is a new issue. I believe it is related to firefox not firing an `unload` event in the iframes, or something similar.

If possible, could you verify that this is the case? Since it's not a quick fix as I expected I will not be able to look into fixing it until I get home from work.

**Comment by nevcos** [comment]
Ok @tejacques,

I've updated the library to v0.2.12 and It didn't change the behavior, so I've started debuging it.

I've added a lot of logs to check what's going wrong, and I ended with this:

![race_condition_2](https://cloud.githubusercontent.com/assets/656065/11480378/11842b0e-978f-11e5-85d6-71ecd53aa997.png)

The problem seems that the old MASTER updates the TAB_KEYS on unloading (with himself as MASTER) and the SLAVE tab manages this event right after declaring himself as a MASTER... so it's demoted to SLAVE again because of the late event.

I'll continue updating.

**Comment by nevcos** [comment]
I think that just removing all handlers on unload fixes the issue:

```
	function unload() {
		window.removeEventListener('storage', onStorageEvent);
		window.removeEventListener('beforeunload', unload);
		window.removeEventListener('DOMContentLoaded', swapUnloadEvents);
		eventHandler.removeListener(util.eventTypes.tabClosed, onTabClosed);
		eventHandler.removeListener(util.eventTypes.tabUpdated, onTabUpdated);
		eventHandler.removeListener(util.eventTypes.tabPromoted, onTabPromoted);
		// ...
	} 
```

I made some tests and it's working ok!

**Comment by tejacques** [comment]
What you said makes a lot of sense. I think there are some edge cases for recoverable unloads, though. Would you mind making a PR with your changes? Would be very helpful for getting the fix out to the masses.

I think here is the full solution:

in `unload`:
* destruct eventHandler via `eventHandler.destructor()` -- this removes all listeners. Or perhaps simply disable the eventHandler with some new `disable()` and `enable()` methods.
* mark handler as destructed/disabled

in `swapUnloadEvents`:
* `eventHandler.enable()` or re-setup if destructed.

After writing it out, I prefer the `enable()` and `disable()` approach.

I can try to do this tonight, or if you would like to give it a go and submit PR that would be very helpful. Thanks for your efforts in improving the library!

**Comment by nevcos** [comment]
Cool! I would be proud to contribute with a PR. Maybe tomorrow I can do it (for today I'll leave just as a temporary fix on the code).

Thanks

**Comment by tejacques** [comment]
Sounds good. Let me know if you are able to get to this. If you aren't I will work on it tonight. Thanks!

**Comment by nevcos** [comment]
@tejacques didn't have available time yesterday, neither today. Feel free to do it if you have a chance.
Thanks

**Comment by tejacques** [comment]
So I realized the issue here isn't really that the tab continues to handle events. That's actually somewhat desirable in the case where the tab resumes (before `DOMContentLoaded` has swapped them). The real issue is that in firefox after the unload event fires, it can still handle other events. This is also potentially possible in `beforeunload` as well.

There are some events then that we want to queue (anything from localStorage) if we are unloading, which we then want to flush if it is a `beforeunload` event that gets cancelled.

Working on and testing a solution here, but it's pretty tricky to get right.
